SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `Usuario`;

CREATE TABLE `Usuario` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(100) NOT NULL,
  `LAST_NAME` VARCHAR(100) NOT NULL,
  `USERNAME` VARCHAR(50) NOT NULL UNIQUE,
  `EMAIL` VARCHAR(150) NOT NULL UNIQUE,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `STATUS_VALIDACAO` BOOLEAN DEFAULT FALSE,
  `RECOVERY_TOKEN` VARCHAR(255) DEFAULT NULL,
  `TOKEN_EXPIRES` DATETIME DEFAULT NULL,
  `INCLUIDO_POR` VARCHAR(50) DEFAULT NULL,
  `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `ALTERADO_POR` VARCHAR(50) DEFAULT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
